### ISSUE TITLE
[server] yarn setup-database fails

### ISSUE THREAD

**Issue by thelordoftheboards** [MachineAcuity/rebar#468]
When `PORT` is missing in `.env` (as it may in deployment with PM2), `setup-database` fails:

```
TASK [rebar-instance-node-deploy : Deploy | Setup database - perform migrations] *************************************************************************************************************************************************************************************
fatal: [142.93.95.22]: FAILED! => {"changed": true, "cmd": "export NODE_ENV=development && cd /rbr/rebar/rebar && node units/rb-appbase-server/setupDatabase", "delta": "0:00:02.784556", "end": "2018-11-18 22:50:53.015703", "msg": "non-zero return code", "rc": 1, "start": "2018-11-18 22:50:50.231147", "stderr": "/mnt/gluster/rebar/rebar/rebar/units/rb-persister-cassandra/graphql/WinstonTransportCassandra.js:17\nthrow new Error('rb-base-server/server.js requires the environment variable PORT to be set');\n^\n\nError: rb-base-server/server.js requires the environment variable PORT to be set\n    at Object.<anonymous> (/mnt/gluster/rebar/rebar/rebar/units/rb-persister-cassandra/graphql/WinstonTransportCassandra.js:17:7)\n    at Module._compile (internal/modules/cjs/loader.js:688:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)\n    at Module.load (internal/modules/cjs/loader.js:598:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:529:3)\n    at Module.require (internal/modules/cjs/loader.js:636:17)\n    at require (internal/modules/cjs/helpers.js:20:18)\n    at Object.<anonymous> (/mnt/gluster/rebar/rebar/rebar/units/rb-persister-cassandra/graphql/PersisterCassandra.js:7:57)\n    atModule._compile (internal/modules/cjs/loader.js:688:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)\n    at Module.load (internal/modules/cjs/loader.js:598:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:529:3)\n    at Module.require (internal/modules/cjs/loader.js:636:17)\n    at require (internal/modules/cjs/helpers.js:20:18)", "stderr_lines": ["/mnt/gluster/rebar/rebar/rebar/units/rb-persister-cassandra/graphql/WinstonTransportCassandra.js:17", "throw new Error('rb-base-server/server.js requires the environment variable PORT to be set');", "^", "", "Error: rb-base-server/server.js requires the environment variable PORT to be set", "    at Object.<anonymous> (/mnt/gluster/rebar/rebar/rebar/units/rb-persister-cassandra/graphql/WinstonTransportCassandra.js:17:7)", "    at Module._compile (internal/modules/cjs/loader.js:688:30)", "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)", "    at Module.load (internal/modules/cjs/loader.js:598:32)", "    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)", "    at Function.Module._load (internal/modules/cjs/loader.js:529:3)", "    at Module.require (internal/modules/cjs/loader.js:636:17)", "    at require (internal/modules/cjs/helpers.js:20:18)", "    at Object.<anonymous> (/mnt/gluster/rebar/rebar/rebar/units/rb-persister-cassandra/graphql/PersisterCassandra.js:7:57)", "    at Module._compile (internal/modules/cjs/loader.js:688:30)", "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)", "    at Module.load (internal/modules/cjs/loader.js:598:32)", "    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)", "    at Function.Module._load (internal/modules/cjs/loader.js:529:3)", "    at Module.require (internal/modules/cjs/loader.js:636:17)", "    at require (internal/modules/cjs/helpers.js:20:18)"], "stdout": "", "stdout_lines": []}
```

**Comment by thelordoftheboards** [comment]
This has been since fixed.
